adding the vuevalidate
codecampleipzig/devhaus pull request #49
Opened 2020-10-02 13:12 UTC by BreakingBad111

adding vuelidate of password and email

2020-10-03 18:00 UTC, DorianWilhelm requested changes

2020-10-03 18:00 UTC, DorianWilhelm commented on frontend/src/views/Auth.vue
> +        await this.bindProfiles();
Where does this come from?

2020-10-03 18:00 UTC, DorianWilhelm commented on frontend/src/views/Auth.vue
> +      }
here is an else missing, b/c signup is called everytime

2020-10-03 18:00 UTC, DorianWilhelm commented on frontend/src/views/Auth.vue
> +        await this.bindProfiles();
where does this come from?

2020-10-03 18:00 UTC, DorianWilhelm commented
Signin and signup is not working!

2020-10-06 08:57 UTC, closed without merging

2020-10-06 08:58 UTC, gabrielheinrich commented
See new pull request